name: Build and deploy site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # =====================================================
      # Clone submodules
      # =====================================================

      - name: Check out submodules
        run: |
          make submodules

      # =====================================================
      # Build
      # =====================================================
      # - uses: quarto-dev/quarto-actions/setup@v2

      - name: Build shinylive
        run: |
          make all

      # =====================================================
      # Commit to gh-pages branch
      # =====================================================
      # Name and email are needed to push.
      - name: Configure git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Push to gh-pages branch
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          export SHA_SHORT=$(git rev-parse --short HEAD)
          git checkout -B gh-pages
          # Copy site/ to docs/, and turn symlinks into actual files/dirs.
          cp -LR site docs
          touch docs/.nojekyll
          git add docs
          git commit -m"Build docs/ for $SHA_SHORT"

          git log -n 4 --pretty=oneline --simplify-by-decoration

          git push -f origin gh-pages:gh-pages
      # =====================================================
      # Run playwright tests
      # =====================================================
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
